dist: xenial

language: python

python:
    - '2.7'
    - '3.5'
    - '3.6'
    - '3.7'
    - '3.8'
    - 'nightly'

matrix:
  allow_failures:
    - python: 'nightly'

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - libhdf5-dev
      - python-h5py
      - python3-h5py
      - python-numpy
      - python3-numpy
      - python-vtk6

before_install:
  - pip install -U pytest pytest-cov

install:
  - pip install .

script:
  - cd test/ && pytest --cov meshio

after_success:
  - bash <(curl -s https://codecov.io/bash)
